# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sympli', '0003_auto_20170703_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
